// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using l14_coffeeAPI.Migrations;

#nullable disable

namespace l14_coffeeAPI.Migrations
{
    [DbContext(typeof(LessonDbContext))]
    [Migration("20220812162142_CreateCoffeeSchema")]
    partial class CreateCoffeeSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("l14_coffeeAPI.Models.Coffee", b =>
                {
                    b.Property<int>("CoffeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Price")
                        .HasColumnType("REAL");

                    b.HasKey("CoffeeId");

                    b.ToTable("Coffee");

                    b.HasData(
                        new
                        {
                            CoffeeId = 1,
                            Description = "Freshly pulled double espresso with steamed milk",
                            Name = "Cappuccino",
                            Price = 3.9900000000000002
                        },
                        new
                        {
                            CoffeeId = 2,
                            Description = "Flavorful espresso topped with hot water",
                            Name = "Americano",
                            Price = 2.4900000000000002
                        });
                });

            modelBuilder.Entity("l14_coffeeAPI.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
